import type { Guide } from './presenterGuides.ts';

export const OPENING_GUIDE: Guide = {
  foundations: 'A apresentação acompanha modelos de linguagem: sistemas que processam representações de texto e podem gerar continuações. IA é uma categoria mais ampla, que também inclui sistemas de classificação, visão e outras tarefas. O percurso da aula separa treinamento, entrada, contexto, processamento, geração, ferramentas e conferência. Todas as animações são demonstrações preparadas; não há um modelo externo respondendo ao vivo. Os oito passos da abertura introduzem ideias que serão explicadas nos capítulos seguintes.',
  glossary: 'IA: área de sistemas que realizam tarefas associadas a capacidades como reconhecimento e previsão.\nModelo: componente com regras ou parâmetros para transformar entradas em saídas.\nModelo de linguagem: modelo que trabalha com padrões e probabilidades de sequências de linguagem.\nAssistente: produto que pode combinar modelo, interface e ferramentas.\nDemonstração didática: exemplo preparado para explicar, sem reproduzir toda a tecnologia real.',
  example: 'Comece dizendo: “Você escreve uma pergunta e recebe uma resposta. O que acontece no meio? Pensem no começo de uma mensagem: ‘Hoje eu quero…’. Vocês conseguem imaginar várias continuações. Um modelo de linguagem também trabalha com possibilidades, mas faz isso por cálculos aprendidos com dados. Vamos abrir esse caminho em partes.” Não prometa que o exemplo humano descreve consciência ou intenção da máquina.',
  demonstration: '1. Deixe a abertura na etapa 1 e leia a pergunta do título.\n2. Use “Começar pela pergunta: ela pensa como a gente?” ou “Próxima etapa” no controle para entrar na descoberta.\n3. Avance uma etapa por vez: aparência humana, treinamento, tokens, contexto, geração, limites e convite.\n4. O botão “Descobrir por dentro” pula diretamente ao primeiro capítulo; use-o só se quiser encurtar a abertura.\n5. Comece o cronômetro manualmente em “Iniciar cronômetro”. Auto-Play e cronômetro são controles diferentes.',
  stages: [
    '“Você faz uma pergunta. Ela responde. Mas o que acontece entre esses dois momentos? Hoje vamos acompanhar esse caminho: como o texto entra, o que o modelo aprendeu, como o contexto participa e por que a resposta pode acertar ou errar. As imagens são exemplos preparados para explicar o processo. Nosso foco será o modelo de linguagem.”',
    '“Quando uma conversa parece humana, podemos sentir que existe alguém pensando do outro lado. A aparência da conversa, sozinha, não demonstra que o processo seja igual ao nosso. Vamos examinar mecanismos observáveis: entradas, representações, cálculos e saídas. Não precisamos resolver hoje a discussão filosófica sobre consciência para entender essas partes.”',
    '“Antes da conversa, há treinamento. Imaginem praticar arremessos: observar o erro ajuda a ajustar a próxima tentativa. Numa rede, quem muda são parâmetros numéricos. Muitos exemplos orientam esses ajustes. Mais adiante vamos mostrar exatamente o que significam previsão, comparação e peso; por enquanto, guardem que treinamento acontece antes do uso normal.”',
    '“Quando digitamos, o texto precisa ganhar uma representação numérica. Ele é recortado em tokens, que podem ser palavras, partes delas ou sinais. Pensem em peças que compõem uma sequência. A animação mostra a transformação de forma simplificada. Não precisamos decorar os códigos; precisamos entender que texto e números estão conectados por uma representação.”',
    '“Se eu disser só banco, vocês podem pensar numa agência ou num assento. Se acrescento praça, uma interpretação ganha força. Se acrescento depósito, outra ganha. O contexto orienta a leitura. Na rede isso acontece por operações com representações; não por uma pessoa escondida escolhendo o sentido.”',
    '“A resposta pode ser construída um token por vez. Cada escolha passa a fazer parte do contexto da próxima. Vamos fazer uma comparação oral: ‘Hoje eu quero…’. Se vocês escolhem estudar, a continuação pode ser diferente de descansar. A analogia mostra o encadeamento; no modelo real as unidades não são sempre palavras inteiras.”',
    '“Um texto fluente pode conter um erro. Imaginem uma frase com nome completo, data e título de um prêmio: os detalhes podem parecer confiáveis mesmo se forem inventados. Precisamos de evidência que sustente a informação, e não apenas de um tom seguro. Este cuidado acompanhará toda a apresentação.”',
    '“Agora vamos observar cada parte, trocar exemplos e explicar as mudanças com nossas palavras. A matemática está disponível como aprofundamento, mas a primeira meta é entender o caminho da pergunta à resposta. Se aparecer um termo novo, vamos defini-lo com um exemplo antes de seguir. Começamos pelas peças do texto: os tokens.”',
  ],
  expected: 'Não existe uma resposta única obrigatória para a pergunta inicial. Aproveite hipóteses como “ela pesquisa”, “ela lembra” e “ela calcula” para anunciar distinções: ferramentas podem pesquisar; contexto e armazenamento são diferentes; o modelo faz cálculos com parâmetros aprendidos. Não confirme todas as hipóteses como se fossem equivalentes.',
  questions: '“Isso é uma IA respondendo agora?” Não; esta apresentação usa animações e simuladores locais preparados.\n“IA e chatbot são a mesma coisa?” Não. Chatbot é uma interface ou aplicação; IA é mais ampla.\n“Ela pensa ou sente?” A fluência do texto não resolve essa questão. Nesta aula vamos explicar mecanismos, sem atribuir experiência humana à rede.',
  shortcut: 'Diga a pergunta do título, complete “Hoje eu quero…” com a turma e anuncie três ideias: padrões aprendidos, contexto e conferência. Use “Descobrir por dentro” para abrir tokens. Não tente resumir todos os termos técnicos na abertura.',
  transition: '“Para processar linguagem, o sistema precisa representar o texto. Vamos acompanhar a pergunta sendo dividida em peças.”',
};

export const FINALE_GUIDE: Guide = {
  foundations: 'A tela final é um mapa de conhecimento. Cada ponto representa uma nota de texto; cada linha representa uma ligação entre ideias. A forma de cérebro é uma metáfora visual. Uma rede neural treinada transforma números e tem parâmetros ajustados; este mapa organiza documentos. O cofre do Obsidian é uma pasta de arquivos Markdown ligados entre si. O pacote da apresentação contém 493 notas e 984 ligações representadas no mapa; é material para continuar estudando, não um modelo de IA.',
  glossary: 'Nota: arquivo ou texto sobre uma ideia.\nLigação: referência entre duas notas ou temas.\nGrafo: representação de pontos e relações.\nMarkdown: formato de texto simples com marcações de títulos e links.\nCofre do Obsidian: pasta de notas aberta pelo aplicativo.\nMetáfora: comparação para explicar, com limites; não uma identidade entre os sistemas.',
  example: '“Vamos ligar tokens, contexto e geração. Tokens são as peças. O contexto reúne informações disponíveis. A geração escolhe novas peças considerando esse contexto. Agora liguem erro e fonte: uma resposta pode ser plausível sem ter apoio, então consultamos evidências. As linhas do mapa ajudam a lembrar essas relações; não executam os cálculos de um modelo.”',
  demonstration: '1. Em Comandos, clique “Mostrar as primeiras ideias”. Faça uma pausa com poucos pontos visíveis.\n2. Clique “Conectar as ideias”: o mapa cresce.\n3. Clique “Revelar a rede inteira” e espere a turma observar as 493 notas.\n4. Clique “Fazer a rede acender” para destacar caminhos e liberar as perguntas.\n5. Escolha uma das três perguntas e leia a explicação correspondente. Em “Explorar um tema”, selecione um assunto para abrir uma nota; escolha “Rede inteira” para sair.\n6. O link “Levar esta rede para o Obsidian” fica na projeção. Baixe o ZIP, extraia a pasta e abra-a como cofre no Obsidian. O aplicativo não abre automaticamente só com o clique.',
  stages: [
    '“Vocês viram as peças separadas. Agora quero mostrar como podemos organizar as relações entre elas.” Mostre poucos pontos e faça uma pausa de três segundos. “Cada ponto aqui é uma nota de texto. Cada linha conecta ideias. Não estamos vendo neurônios reais; estamos construindo um mapa para estudar.”',
    'Clique “Conectar as ideias”. Diga: “Tokens se conectam a contexto porque o contexto é representado por tokens. Contexto se conecta a geração porque o que está disponível orienta a próxima escolha. Uma ideia ajuda a explicar outra. Essa é a função das ligações no mapa.”',
    'Clique “Revelar a rede inteira” e espere cerca de cinco segundos antes de falar. “São 493 notas organizadas em temas, com 984 ligações neste mapa. O número impressiona, mas o valor está em conseguir voltar a uma pergunta e seguir relações para estudar. Mais notas, sozinhas, não garantem compreensão.”',
    'Clique “Fazer a rede acender”. Diga: “As luzes destacam caminhos entre ideias. A forma de cérebro é uma metáfora. Num modelo neural, há operações numéricas e pesos aprendidos; aqui, temos textos e referências. Os desenhos podem se parecer, mas os mecanismos são diferentes.”',
    'Escolha “Por que a IA pode errar?”. Diga: “Ela produz continuações a partir dos padrões aprendidos e do contexto. Uma continuação pode soar boa e estar errada. Ligamos geração, probabilidade e fontes para lembrar por que precisamos conferir.” Se escolher outra pergunta, use as respostas completas na seção de dúvidas destas notas.',
    'Em “Explorar um tema”, escolha “Rede neural”. Leia a nota aberta e diga: “Esta nota explica o conceito; ela não é uma unidade de cálculo treinada. A referência entre duas notas também não é um peso ajustado por treinamento.” Volte a “Rede inteira” antes de escolher outra pergunta, para deixar a resposta visível.',
    '“Vocês podem continuar explorando depois. O link baixa uma pasta compactada com notas de verdade. Extraímos o ZIP e abrimos a pasta como cofre no Obsidian. Cada link permite caminhar para uma ideia relacionada. Não é necessário instalar algo agora para acompanhar esta apresentação.” Mostre onde fica o link sem interromper a fala para configurar um aplicativo.',
    '“A próxima conexão pode ser sua: qual pergunta você acrescentaria ao mapa?” Ouça uma sugestão e relacione com um tema concreto. Exemplo: “por que ela esquece?” liga contexto e memória; “por que inventou uma fonte?” liga erros e verificação. Se não souber uma resposta, registre a pergunta e diga que precisa conferir, sem inventar para preencher o silêncio.',
  ],
  expected: 'Aceite relações justificadas. Exemplo: contexto influencia geração; ferramentas podem fornecer dados; evidências ajudam a conferir afirmações. Corrija a ideia de que as 493 notas sejam neurônios ou de que uma ligação entre textos prove que uma afirmação é verdadeira.',
  questions: '“Por que a IA pode errar?” Porque produzir uma continuação plausível não garante apoio factual. Dados, contexto e geração podem introduzir falhas; compare as afirmações com fontes.\n“Como a IA ajuda no dia a dia?” Pode apoiar um rascunho, uma comparação ou a organização de material. Exemplo: fornecer um regulamento, pedir um resumo e conferir cada regra citada no original.\n“Por que mais informação não basta?” Informação irrelevante, contraditória ou inacessível pode não ajudar. Exemplo: cem páginas de receitas não substituem a condição específica “sem leite” do pedido.\n“Isso é o cérebro da IA?” Não: é um mapa de notas inspirado no Obsidian.\n“Não sei responder uma pergunta da plateia.” Diga: “Essa pergunta exige uma verificação que ainda não fiz. Vou registrá-la para conferir com uma fonte.”',
  shortcut: 'Revele em três cliques, relacione tokens→contexto→geração e deixe explícito que são notas, não neurônios. Mostre o download e termine com uma pergunta da turma. Não apresse a pausa de observação da rede inteira.',
  transition: '“Entender as partes ajuda a usar a IA com mais clareza: formular o pedido, observar o contexto e conferir a resposta. Obrigado; vamos às perguntas.”',
};

export const QUIZ_EXPLANATIONS = [
  'C é correta: uma palavra pode ser representada por vários tokens, dependendo do tokenizador. A erra ao impor uma regra a todos os modelos. B também erra: escrever em português não cria equivalência de um token por palavra. Retome extraordinário dividido em peças como exemplo ilustrativo, sem afirmar que aquele recorte é universal.',
  'A é correta: o treinamento ajusta parâmetros, entre eles os pesos que influenciam os cálculos. B descreve uma pessoa escondida, que não faz parte do mecanismo demonstrado. C reduz o modelo a um catálogo de respostas fixas, o que não explica a generalização. Retome o exemplo gato/miau e os passos prever, comparar e ajustar.',
  'B é correta: praça e conta fornecem pistas de contexto. A não distingue os usos, porque banco mantém o mesmo número de letras. C é um detalhe visual sem relação com a interpretação linguística. Leia “sentei no banco da praça” e “fui ao banco fazer um depósito” para demonstrar a diferença.',
  'C é correta: temperatura muda a distribuição usada para escolher continuações. A confunde amostragem com consulta a fontes: mudar temperatura não executa uma pesquisa. B confunde variação com inteligência. Retome a urna: dar mais chance a papéis diferentes não confere se o que está escrito neles é verdadeiro.',
  'B é correta: o contexto tem limites e o sistema pode selecionar ou resumir conteúdo. A ignora esses limites. C confunde histórico visível com entrada efetivamente enviada ao modelo; deixar a aba aberta não garante disponibilidade integral. Retome os cartões e a exigência “sem leite” que pode se perder num resumo.',
  'A é correta: uma fonte precisa existir e sustentar a afirmação. B confunde ter uma citação com ter evidência válida. C pode apenas repetir o mesmo erro. Procedimento: abrir a fonte, localizar o trecho, comparar com o que foi afirmado e reconhecer quando não há apoio suficiente.',
];
