import { useId } from 'react';
import { ArrowRight, Bot, Check, CircleCheck, FileText, LockKeyhole, ShieldCheck, X } from 'lucide-react';
import type { Command, Sim } from '../../shared/engine';
import { MAZE, START, GOAL, probabilities, logic, topologicalLayers, minimax, growth, missionChecks, TRANSITIONS } from '../../shared/engine';
import { LESSONS, QUIZ } from '../../shared/curriculum';
import { OpeningScene, FinaleScene } from './ShowScenes';

const COLORS = ['#f3c56c', '#7dd6e5', '#bbabed', '#7edbbd', '#f297aa', '#cbd5e1'];
const format = (number: number | bigint) => number.toLocaleString('pt-BR');
function Graph({ nodes, edges, highlighted = [], directed = true, active = [] }: { nodes: { id: string; label: string; x: number; y: number }[]; edges: string[]; highlighted?: string[]; directed?: boolean; active?: string[] }) {
  const arrow = useId().replace(/:/g, '');
  return <svg className="live-graph" viewBox="0 0 640 340" role="img" aria-label="Grafo de nós e conexões"><defs><marker id={arrow} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#8193aa" /></marker></defs>{edges.map(edge => { const [a, b] = edge.split('>'), source = nodes.find(n => n.id === a), target = nodes.find(n => n.id === b); if (!source || !target) return null; const selected = highlighted.some((id, index) => id === a && highlighted[index + 1] === b || !directed && id === b && highlighted[index + 1] === a); return <line key={edge} x1={source.x + (target.x - source.x) / Math.hypot(target.x - source.x, target.y - source.y) * 31} y1={source.y + (target.y - source.y) / Math.hypot(target.x - source.x, target.y - source.y) * 31} x2={target.x - (target.x - source.x) / Math.hypot(target.x - source.x, target.y - source.y) * 34} y2={target.y - (target.y - source.y) / Math.hypot(target.x - source.x, target.y - source.y) * 34} stroke={selected ? '#7edbbd' : '#607086'} strokeWidth={selected ? 5 : 2} markerEnd={directed ? 'url(#' + arrow + ')' : undefined} />; })}{nodes.map(n => <g key={n.id}><circle cx={n.x} cy={n.y} r="29" fill={active.includes(n.id) ? '#295443' : '#202b3b'} stroke={highlighted.includes(n.id) || active.includes(n.id) ? '#7edbbd' : '#7e94b1'} strokeWidth="2" /><text x={n.x} y={n.y + 6} fill="#edf3ff" textAnchor="middle" fontSize="19" fontWeight="600">{n.id}</text><text x={n.x} y={n.y + 49} fill="#aebdd1" textAnchor="middle" fontSize="14">{n.label}</text></g>)}</svg>;
}
export function SimVisual({ module, sim, send, stage = 0 }: { module: number; sim: Sim; send: (command: Command) => void; stage?: number }) {
  const v = sim.values;
  if (module === 0) return <OpeningScene send={send} stage={stage} />;
  if (module === 1) {
    const options = Number(v.options), length = Number(v.length), total = options ** length;
    const sequences = Array.from({ length: Math.min(total, 64) }, (_, i) => Array.from({ length }, (_, j) => Math.floor(i / options ** (length - j - 1)) % options));
    return <div className="factory-visual"><div className="formula-strip"><span>{options} opções</span><X size={18} /><span>{length} posições</span><ArrowRight size={20} /><strong key={total} className="count-arrive">{format(total)}<small>sequências possíveis</small></strong></div><div className="sequence-grid">{sequences.map((sequence, i) => <div className="sequence" key={length + "-" + i} style={{ animationDelay: Math.min(i * 9, 300) + "ms" }}>{sequence.map((value, j) => <span key={j} style={{ background: COLORS[value] }}>{String.fromCharCode(65 + value)}</span>)}</div>)}</div><p className="visual-caption">{total <= 64 ? 'Todas as possibilidades, com ordem e repetição.' : '64 exemplos de ' + format(total) + ' sequências. O restante está agregado no total.'}</p><div className="math-reveal">{options}<sup>{length}</sup> = {Array(length).fill(options).join(' × ')} = {format(total)}</div></div>;
  }
  if (module === 2) {
    const frontier = sim.frontier.map(path => path[path.length - 1]);
    return <div className="maze-visual"><div className="maze-board" role="img" aria-label="Labirinto 7 por 7"><svg viewBox="0 0 350 350" className="maze-lines" aria-hidden="true">{MAZE.flatMap((row, r) => [...row].flatMap((cell, c) => cell === '#' ? [] : [[r + 1, c], [r, c + 1]].filter(([y, x]) => y < 7 && x < 7 && MAZE[y][x] !== '#').map(([y, x]) => <line key={r + ',' + c + '-' + y + ',' + x} x1={c * 50 + 25} y1={r * 50 + 25} x2={x * 50 + 25} y2={y * 50 + 25} stroke="#93a4bf44" strokeWidth="2" />)))}</svg>{MAZE.flatMap((row, r) => [...row].map((cell, c) => { const id = r + ',' + c; return <div key={id} className={'maze-cell ' + (cell === '#' ? 'wall' : sim.path.includes(id) ? 'path' : frontier.includes(id) ? 'frontier' : sim.visited.includes(id) ? 'visited' : '')}>{id === sim.path[sim.path.length - 1] ? <Bot size={22} /> : id === GOAL ? <span>S</span> : id === START ? <span>I</span> : sim.visited.includes(id) ? <Check size={14} /> : <small>{cell === '#' ? '' : r * 7 + c}</small>}</div>; }))}</div><div className="maze-report"><h3>{sim.done ? 'Busca concluída' : 'Uma decisão por vez'}</h3><dl><div><dt>Visitados</dt><dd>{sim.visited.length}</dd></div><div><dt>Na fronteira</dt><dd>{frontier.length}</dd></div><div><dt>Arestas no caminho</dt><dd>{Math.max(0, sim.path.length - 1)}</dd></div></dl><div className="visual-legend"><span>✓ visitado</span><span>Contorno: fronteira</span><span>Verde: caminho atual</span></div><p>Os centros das células são vértices; as linhas representam arestas do grafo.</p><p className="search-frontier">Fronteira: {frontier.slice(0, 8).join(' · ') || 'vazia'}</p></div></div>;
  }
  if (module === 3) return <div className="logic-visual"><div className="logic-circuit"><span className={v.badge ? 'on' : ''}>Crachá<strong>{v.badge ? 'V' : 'F'}</strong></span><b>{v.operator === 'and' ? 'E' : 'OU'}</b><span className={v.permission ? 'on' : ''}>Autorização<strong>{v.permission ? 'V' : 'F'}</strong></span><b>E NÃO</b><span className={v.blocked ? 'on' : ''}>Bloqueio<strong>{v.blocked ? 'V' : 'F'}</strong></span></div><div className={'door-result ' + (logic(v) ? 'allowed' : '')}>{logic(v) ? <ShieldCheck size={42} /> : <LockKeyhole size={42} />}<strong>{logic(v) ? 'Acesso permitido' : 'Acesso negado'}</strong></div>{sim.revealed && <table className="truth-table"><thead><tr><th>Crachá</th><th>Autorização</th><th>Bloqueio</th><th>Resultado</th></tr></thead><tbody>{Array.from({ length: 8 }, (_, i) => ({ badge: Boolean(i & 4), permission: Boolean(i & 2), blocked: Boolean(i & 1), operator: v.operator })).map((row, i) => <tr key={i} className={row.badge === v.badge && row.permission === v.permission && row.blocked === v.blocked ? "current-rule" : ""}><td>{row.badge ? 'V' : 'F'}</td><td>{row.permission ? 'V' : 'F'}</td><td>{row.blocked ? 'V' : 'F'}</td><td>{logic(row) ? 'Permitir' : 'Negar'}</td></tr>)}</tbody></table>}</div>;
  if (module === 4) return <><Graph nodes={[{ id: 'A', label: 'Pergunta', x: 65, y: 170 }, { id: 'B', label: 'Documento', x: 225, y: 75 }, { id: 'C', label: 'Referência', x: 225, y: 255 }, { id: 'D', label: 'Evidência', x: 405, y: 75 }, { id: 'E', label: 'Contexto', x: 405, y: 255 }, { id: 'F', label: 'Resposta', x: 570, y: 170 }]} edges={sim.edges} highlighted={sim.path} directed={Boolean(v.directed)} /><div className="math-reveal">{sim.path.length ? sim.path.join(' → ') : sim.done ? 'Não há caminho entre os vértices escolhidos.' : 'A estrutura da rede determina os caminhos possíveis.'}</div></>;
  if (module === 5) { const n = Number(v.stones), tree = minimax(n); return <div className="strategy-visual"><div className="stone-pile">{Array.from({ length: n }, (_, i) => <span key={i}>{i + 1}</span>)}{n === 0 && <CircleCheck size={48} />}</div><div className="strategy-status">{sim.done ? sim.status : 'Vez do jogador ' + (sim.tick % 2 + 1)}<small>Quem retirar a última peça vence.</small></div><div className="decision-tree"><div className="tree-root">{n} peças</div><div className="tree-branches">{tree.choices.map(choice => <div key={choice.move}><span>retirar {choice.move}</span><strong>{n - choice.move} restantes</strong>{sim.revealed && <small>{choice.winning ? 'Vitória forçável' : 'Sem vitória garantida'}</small>}</div>)}</div></div><p className="visual-caption">{tree.explored} avaliações de estados na busca minimax com memória. Algoritmos programados.</p></div>; }
  if (module === 6) { const mod = Number(v.modulus), initial = Number(v.position), shift = Number(v.offset), end = (initial + shift) % mod; const point = (position: number, radius: number) => ({ x: 180 + Math.sin(position / mod * Math.PI * 2) * radius, y: 180 - Math.cos(position / mod * Math.PI * 2) * radius }); const a = point(initial, 95), b = point(end, 115); return <div className="clock-visual"><svg viewBox="0 0 360 360" role="img" aria-label={'Relógio de ' + mod + ' posições, resultado ' + end}><circle cx="180" cy="180" r="145" stroke="#526079" strokeWidth="2" fill="#172034" />{Array.from({ length: mod }, (_, i) => { const p = point(i, 126); return <text x={p.x} y={p.y + 6} textAnchor="middle" key={i} fill={i === end ? '#f7c66f' : '#a7b5cb'} fontSize="19">{i}</text>; })}<line x1="180" y1="180" x2={a.x} y2={a.y} stroke="#83d4e6" strokeWidth="6" strokeLinecap="round" /><line x1="180" y1="180" x2={b.x} y2={b.y} stroke="#f7c66f" strokeWidth="5" strokeLinecap="round" /><circle cx="180" cy="180" r="8" fill="#eef3ff" /></svg><div><span className="live-eyebrow">A POSIÇÃO FINAL</span><div className="clock-equation">({initial} + {shift}) mod {mod}<strong>= {end}</strong></div><p>Azul: início · dourado: resultado</p><p className="clock-rope">RoPE: pares vetoriais e múltiplas frequências. Este relógio representa apenas a ideia de rotação.</p></div></div>; }
  if (module === 7) { const order = topologicalLayers(sim.edges); return <><Graph nodes={[{ id: 'P', label: 'Pesquisar', x: 75, y: 170 }, { id: 'V', label: 'Verificar', x: 310, y: 70 }, { id: 'E', label: 'Escrever', x: 310, y: 260 }, { id: 'R', label: 'Revisar', x: 565, y: 170 }]} edges={sim.edges} active={sim.visited} /><div className={'math-reveal ' + (order.cycle ? 'danger' : '')}>{order.cycle ? 'Ciclo detectado: não existe ordenação topológica.' : order.layers.map(layer => '[' + layer.join(' ∥ ') + ']').join(' → ')}</div><p className="visual-caption">{sim.tick ? sim.status : 'Mesma camada: tarefas independentes podem executar em paralelo.'}</p></>; }
  if (module === 8) { const drawers = Number(v.drawers), objects = Number(v.objects), counts = Array.from({ length: drawers }, (_, i) => sim.bins.filter(bin => bin === i).length); return <div className="drawers-visual"><div className="drawer-row">{counts.map((count, i) => <button key={i} disabled={sim.done} onClick={() => send({ type: 'action', key: 'place', value: i })} className={'drawer ' + (count > 1 ? 'collision' : '')}><span>Gaveta {i}</span><div>{sim.bins.map((bin, index) => bin === i ? <b key={index}>{index}</b> : null)}</div><small>{count > 1 ? 'Colisão: ' + count + ' objetos' : count + ' objeto'}</small></button>)}</div><div className="formula-strip"><span>{sim.bins.length} / {objects} distribuídos</span><strong>⌈{objects}/{drawers}⌉ = {Math.ceil(objects / drawers)}</strong></div><p className="visual-caption">{objects > drawers ? 'Ao concluir a distribuição, pelo menos uma gaveta terá mais de um objeto.' : 'Uma colisão é possível, mas não obrigatória.'}</p><div className="math-reveal">h(x) = x mod {drawers}<small>Cada objeto vai para exatamente uma gaveta.</small></div></div>; }
  if (module === 9) { const probs = probabilities(Number(v.temperature)), total = sim.counts.reduce((a, b) => a + b, 0); return <div className="probability-visual"><div className="probability-head"><span>Vocabulário ilustrativo</span><span>Teórica / observada</span></div>{['aprende', 'conecta', 'imagina', 'reinventa'].map((word, i) => <div className="probability-row" key={word}><div><strong>{word}</strong><span>{(probs[i] * 100).toFixed(1)}% / {total ? (sim.counts[i] / total * 100).toFixed(1) : '0'}%</span></div><div className="probability-track"><span style={{ width: probs[i] * 100 + '%', background: COLORS[i] }} /></div><div className="observed-track"><span style={{ width: (total ? sim.counts[i] / total * 100 : 0) + '%', background: COLORS[i] }} /></div></div>)}<div className="formula-strip"><span>Barra cheia: probabilidade<br />Barra fina: frequência observada</span><strong>{format(total)}<small>amostras · semente 42</small></strong></div></div>; }
  if (module === 10) return <div className="state-machine"><div className="state-flow">{Object.keys(TRANSITIONS).map((state, i) => <div key={state} className={sim.status === state ? 'active' : ''}><span>{String(i + 1).padStart(2, '0')}</span><strong>{state}</strong>{sim.status === state && <Bot size={21} />}</div>)}</div><div className="math-reveal">Estado atual: {sim.status}</div><ul className="simulation-log">{sim.log.slice(-4).map((line, i) => <li key={i} className={line.startsWith('Transição inválida') ? 'danger' : ''}>{line}</li>)}</ul></div>;
  if (module === 11) { const n = Number(v.n), labels = [['linear', 'n'], ['quadratic', 'n²'], ['exponential', '2ⁿ'], ['factorial', 'n!']]; const selected = growth(n, String(v.family)); return <div className="growth-visual"><div className="growth-bars">{labels.map(([key, label], i) => { const count = growth(n, key); return <div className={v.family === key ? 'selected' : ''} key={key}><span>{label}</span><div><i style={{ width: Math.max(1, Math.log10(Number(count) + 1) / Math.log10(Number(growth(n, 'factorial') > growth(n, 'exponential') ? growth(n, 'factorial') : growth(n, 'exponential')) + 1) * 100) + '%', background: COLORS[i] }} /></div><strong>{count.toString().length > 15 ? Number(count).toExponential(2) : format(count)}</strong></div>; })}</div><p className="visual-caption">Comprimento das barras em escala logarítmica. Valores são contagens exatas.</p><div className="growth-estimate"><span>Estimativa a 1 milhão de estados/s</span><strong>{(Number(selected) / 1e6).toLocaleString('pt-BR', { maximumFractionDigits: 3 })} s</strong><small>Taxa hipotética, não uma medição.</small></div>{v.measuredCount !== undefined && <div className="measurement">Medição real: {format(Number(v.measuredCount))} iterações (n={String(v.measuredN)}) em {Number(v.measuredMs).toFixed(3)} ms, neste servidor.</div>}</div>; }
  if (module === 12) return <div className="mission-visual"><div className="mission-pipeline">{missionChecks(sim).map((check, i) => <div key={check.label} className={i < sim.tick ? check.passed ? 'passed' : 'failed' : !sim.done && i === sim.tick && sim.status !== 'inicial' ? 'checking' : ''}><span className="mission-node">{i < sim.tick ? check.passed ? <Check size={25} /> : <X size={25} /> : <span>{i + 1}</span>}</span><strong>{check.label}</strong><small>{i < sim.tick ? check.passed ? 'Verificado' : 'Bloqueado' : !sim.done && i === sim.tick && sim.status !== 'inicial' ? 'Verificando…' : 'Aguardando execução'}</small></div>)}</div><div className={'mission-result ' + (sim.done && missionChecks(sim).every(c => c.passed) ? 'passed' : '')}>{sim.status !== 'inicial' ? sim.status : 'Pedido → busca de evidência → equipe → resposta'}</div><p className="visual-caption">A lógica autoriza. O grafo localiza. O DAG coordena. A capacidade limita.</p></div>;
  if (module === 13) { const quiz = QUIZ[sim.tick]; return <div className="final-quiz"><span className="live-eyebrow">RODADA {sim.tick + 1} / {QUIZ.length} · VOTAÇÃO POR MÃOS LEVANTADAS</span><h3>{quiz.question}</h3><div className="quiz-options">{quiz.options.map((option, i) => <button key={option} disabled={sim.revealed} aria-pressed={sim.selected === i} className={(sim.selected === i ? 'selected ' : '') + (sim.revealed && i === quiz.answer ? 'correct' : '')} onClick={() => send({ type: 'answer', value: i })}><span>{String.fromCharCode(65 + i)}</span><strong>{option}</strong>{sim.revealed && i === quiz.answer && <Check size={24} />}</button>)}</div>{sim.revealed && <p className="quiz-explanation">{quiz.why}</p>}<div className="quiz-navigation"><button disabled={sim.tick === 0} onClick={() => send({ type: 'quiz', value: sim.tick - 1 })}>Rodada anterior</button><button disabled={sim.tick === 5} onClick={() => send({ type: 'quiz', value: sim.tick + 1 })}>Próxima rodada<ArrowRight size={16} /></button></div></div>; }
  return <FinaleScene send={send} />;
}


