// Spoken and projected language. Formal definitions stay in the presenter's notes.
export const AUDIENCE_COPY: Record<number, Record<string, string>> = {
  0: { example: 'Você escolhe quatro números para uma senha. Parece pouco… até contar todas as possibilidades.', application: 'Escolher uma rota, organizar tarefas e completar uma frase: a IA precisa lidar com muitas possibilidades.', conclusion: 'Você não precisa saber programar para participar. Basta dar um palpite e observar.' },
  1: { example: 'Monte uma fileira de três peças: em cada lugar, escolha amarela, azul ou vermelha.', reveal: 'Cada novo lugar multiplica as possibilidades. Com 3 cores e 3 lugares: 3 × 3 × 3 = 27.', application: 'A IA também monta sequências, escolhendo pequenos pedaços de texto, chamados tokens.', conclusion: 'Se existem tantas opções, como encontrar uma boa escolha sem tentar tudo?' },
  2: { math: 'Encontrar caminhos', example: 'Você está num lugar desconhecido. Explora um corredor até o fim ou olha primeiro todas as saídas próximas?', prediction: 'Qual estratégia encontra a saída com menos passos?', reveal: 'Olhar por camadas encontra a rota com menos passos neste labirinto. Seguir um corredor até o fim pode dar uma volta maior.', application: 'Um robô que procura uma saída e um sistema que planeja tarefas precisam explorar caminhos possíveis.', conclusion: 'Um bom caminho ajuda. Agora imagine que há uma porta que só abre com a regra certa.' },
  3: { example: 'Para entrar no evento, você precisa de ingresso E documento. O que muda se a placa disser OU?', reveal: 'Com E, precisa ter os dois. Com OU, basta um. Uma palavra muda quem consegue entrar.', application: 'Antes de uma IA acessar um arquivo ou executar uma tarefa, o sistema deve conferir se ela tem permissão.', conclusion: 'As palavras conectam regras. E as referências conectam ideias.' },
  4: { math: 'Ideias que se conectam', example: 'Você vê uma receita, descobre um ingrediente e chega a outra receita. Uma ideia abre caminho para outra.', reveal: 'Um link é uma ligação direta. Um caminho passa por várias ligações. Seguir alguém não significa que essa pessoa segue você.', application: 'Mapas de conhecimento ligam assuntos, documentos e fontes. É a ideia que vamos reencontrar no Obsidian, no final.', conclusion: 'Quando você enxerga conexões, começa a perceber as consequências de cada escolha.' },
  5: { math: 'Pensar na próxima jogada', variant: 'Compare jogar ao acaso, pegar o máximo e pensar na resposta do adversário.', reveal: 'Deixe 4 peças para o adversário. Depois, tire o que falta para as duas retiradas somarem 4. Pense uma jogada à frente.', application: 'Em jogos e planejamento, um sistema pode comparar o que acontece depois de cada decisão.', conclusion: 'A estratégia esconde um padrão que se repete. Como os números de um relógio.' },
  6: { short: 'O relógio', math: 'Padrões que dão a volta', example: 'São 2 horas. Você espera 14 horas. O ponteiro dá uma volta e ainda anda mais um pouco.', reveal: 'Uma volta completa não muda a posição do ponteiro. De 2, avançamos 14 e chegamos ao 4.', application: 'Na frase “o cachorro mordeu o homem”, a ordem importa. Modelos de linguagem usam informações de posição para distinguir essa ordem.', conclusion: 'A ordem das palavras muda uma frase. A ordem das tarefas muda um trabalho.' },
  7: { short: 'Tarefas em equipe', math: 'O que vem antes de quê', example: 'Num trabalho em grupo, dá para conferir fontes e escrever juntos. Mas a revisão final precisa esperar o texto.', prediction: 'E se o primeiro passo tiver de esperar pelo último?', reveal: 'Algumas tarefas podem acontecer juntas. Se uma espera pela outra em círculo, ninguém começa.', application: 'Um assistente de IA pode dividir um pedido em pesquisar, escrever e revisar. O fluxo organiza quem espera por quem.', conclusion: 'Mesmo com tudo organizado, ainda precisamos de espaço para guardar o que encontramos.' },
  8: { short: 'As gavetas', math: 'Quando o espaço acaba', example: 'Cinco amigos deixam seus celulares em quatro gavetas. Alguma gaveta terá que receber dois.', prediction: 'Com quatro gavetas, quantos objetos tornam a repetição inevitável?', reveal: 'Cinco objetos, quatro gavetas: pelo menos dois ficam juntos. Não depende de sorte; é falta de espaço.', application: 'Computadores usam códigos curtos para organizar dados. Dois dados diferentes podem acabar com o mesmo código.', conclusion: 'Aqui o resultado era inevitável. Mas e quando só sabemos o que é mais provável?' },
  9: { title: 'Por que a resposta muda?', example: 'Complete “Hoje eu quero…”: dormir, viajar ou estudar? Há várias continuações.', prediction: 'Se uma opção é a favorita, ela precisa aparecer sempre?', reveal: 'A favorita pode não sair. A temperatura muda o espaço dado às outras opções.', application: 'Ao gerar texto, uma IA pode escolher entre continuações possíveis. Soar provável não garante estar certo.', conclusion: 'Escolher uma resposta é uma parte. Saber quando enviá-la é outra.' },
  10: { short: 'Passo a passo', math: 'Cada coisa na sua hora', example: 'Um pedido de comida passa por recebido, confirmado, em preparo e entregue. Não faz sentido entregar antes de preparar.', prediction: 'O assistente deve responder antes de conferir o pedido?', reveal: 'Cada etapa libera certas ações. Se a ação chega na hora errada, o fluxo deve recusá-la.', application: 'Um atendimento pode usar IA para conversar e regras para organizar as etapas de cada pedido.', conclusion: 'Quanto mais caminhos e etapas existem, mais difícil fica verificar todas as possibilidades.' },
  11: { math: 'Quando tentar tudo fica impossível', example: 'Organizar 3 pessoas numa fila é fácil. E testar todas as ordens possíveis de uma turma inteira?', reveal: 'Acrescentar uma pessoa pode multiplicar muito o trabalho. Por isso, “tentar tudo” logo deixa de ser uma boa ideia.', application: 'Sistemas de IA precisam escolher onde gastar tempo: quais caminhos explorar e quando parar.', conclusion: 'Vamos juntar tudo: uma equipe, um pedido e alguns obstáculos para resolver.' },
  12: { example: 'Sua equipe precisa responder a um pedido. Há permissão? A fonte está acessível? As tarefas podem começar? As evidências cabem?', reveal: 'A missão funciona quando as quatro partes se encaixam: permissão, fonte, ordem das tarefas e espaço.', application: 'Uma boa ferramenta de IA depende também de boas fontes, regras claras e conferência dos resultados.', conclusion: 'As peças funcionaram juntas. Agora vamos ver o tamanho da rede que elas formam.' },
  13: { math: 'O que você leva desta conversa', question: 'Depois de experimentar, qual decisão você tomaria?', conclusion: 'Entender uma ideia dá a você poder para questionar, conferir e escolher melhor.' },
  14: { short: 'O cérebro de ideias', title: 'Uma ideia acende muitas outras', math: 'O conhecimento ganha conexões', question: 'E se cada descoberta de hoje acendesse outras ideias?', example: 'Cada ponto é uma nota. Cada linha liga duas ideias. Esse é o nosso mapa de conhecimento.', reveal: 'O “cérebro” é uma metáfora visual: este grafo mostra ideias conectadas, como no Obsidian.', application: 'Você pode levar essa rede, abrir as notas e acrescentar as suas próprias descobertas.', conclusion: 'A próxima conexão pode ser sua.' },
};
