import { AUDIENCE_COPY } from './audience.ts';
export const STAGES = ['A pergunta', 'Um exemplo', 'Seu palpite', 'Experimente', 'E se mudar?', 'Por que acontece?', 'Onde a IA entra', 'A próxima ideia'];
export const STAGE_SECONDS = [45, 45, 60, 120, 60, 60, 60, 30];
export interface Lesson {
  id: number; title: string; short: string; math: string; question: string; example: string;
  prediction: string; variant: string; reveal: string; application: string; limit: string; conclusion: string;
  color: string; minutes: number;
}
export const FORMAL_LESSONS: Lesson[] = [
  { id: 0, title: 'A matemática invisível da IA', short: 'Abertura', math: 'Prever, testar, explicar', question: 'Uma máquina precisa tentar tudo para encontrar uma boa resposta?', example: 'Uma senha com quatro posições e dez símbolos já admite 10.000 sequências.', prediction: 'Neste exemplo, o que gera mais sequências: dobrar as opções ou dobrar o comprimento?', variant: 'Compare 20⁴ com 10⁸: dobre só as opções ou só as posições da senha inicial.', reveal: '20⁴ = 160.000; 10⁸ = 100 milhões. Neste exemplo, dobrar as posições gera 625 vezes mais sequências que dobrar as opções.', application: 'Decisão, busca, representação e coordenação aparecem em sistemas de IA.', limit: 'As experiências são algoritmos didáticos locais. Nenhum modelo externo está respondendo ao vivo.', conclusion: 'Começamos com escolhas simples. O número de possibilidades pode surpreender.', color: '#f7c66f', minutes: 8 },
  { id: 1, title: 'A fábrica de combinações', short: 'Fábrica', math: 'Princípio multiplicativo', question: 'Quantas possibilidades cabem em três escolhas?', example: 'Escolher uma peça para cada posição: roupas, símbolos de senha ou tokens.', prediction: 'Com 3 opções e 3 posições, quantas sequências existem?', variant: 'Mantenha as opções e acrescente uma posição. O total soma ou multiplica?', reveal: 'V opções em cada uma de n posições: Vⁿ sequências, com repetição e ordem relevante.', application: 'Um vocabulário finito permite construir muitas sequências de tokens.', limit: 'Um LLM não enumera todas as frases. Sequências ordenadas com repetição não são combinações sem ordem.', conclusion: 'Muitas possibilidades exigem uma estratégia de busca.', color: '#f7c66f', minutes: 8 },
  { id: 2, title: 'O robô e a saída', short: 'Labirinto', math: 'Grafos, BFS, DFS e backtracking', question: 'Encontrar uma saída é o mesmo que encontrar a menor rota?', example: 'O mesmo labirinto aparece como corredores e como grafo de posições.', prediction: 'Qual estratégia chega à saída pelo menor número de arestas?', variant: 'Troque largura por profundidade, mantendo o labirinto.', reveal: 'BFS explora por camadas. DFS aprofunda um ramo. Backtracking desfaz escolhas quando necessário.', application: 'Busca em espaços de estados aparece em planejamento e resolução de problemas.', limit: 'BFS minimiza arestas em grafos não ponderados ou com pesos iguais. Não descreve literalmente o raciocínio de um LLM.', conclusion: 'O caminho depende tanto da estrutura quanto das regras.', color: '#66dab8', minutes: 8 },
  { id: 3, title: 'O detetive das regras', short: 'Lógica', math: 'Lógica proposicional', question: 'Uma regra aparentemente segura pode abrir a porta errada?', example: 'A porta exige crachá E autorização, sem bloqueio de segurança.', prediction: 'Se usarmos OU no lugar de E, quem passa a entrar?', variant: 'Ative só o crachá. Compare E com OU e revele a tabela-verdade.', reveal: '(C ∧ A) ∧ ¬B exige as duas credenciais e ausência de bloqueio.', application: 'Condições lógicas controlam permissões e ações de ferramentas em sistemas de IA.', limit: 'Uma regra formal correta ainda depende de dados corretos e de requisitos bem definidos.', conclusion: 'Regras também descrevem relações entre elementos.', color: '#f197ac', minutes: 8 },
  { id: 4, title: 'A rede de conexões', short: 'Relações', math: 'Relações e grafos direcionados', question: 'Se um documento aponta para outro, a relação vale nos dois sentidos?', example: 'Uma biblioteca de seis documentos conectados por referências.', prediction: 'Existe um caminho de A até F? E de F até A?', variant: 'Transforme a rede em simétrica ou remova uma conexão.', reveal: 'Arestas diretas e caminhos são coisas diferentes. Simetria exige o par inverso.', application: 'Grafos de conhecimento e recomendações usam relações para localizar informações.', limit: 'Existir um caminho não prova que uma recomendação é boa ou que um fato é verdadeiro.', conclusion: 'Na próxima etapa, conexões viram decisões de um jogo.', color: '#79cfe5', minutes: 8 },
  { id: 5, title: 'O duelo de estratégias', short: 'Estratégias', math: 'Árvores de decisão e minimax', question: 'Pegar o máximo agora sempre é a melhor jogada?', example: 'Há 7 peças. Cada jogador retira 1, 2 ou 3. Quem tira a última vence.', prediction: 'Qual retirada deixa o adversário sem uma vitória garantida?', variant: 'Compare aleatório reproduzível, guloso e minimax com a mesma quantidade inicial.', reveal: 'Estados múltiplos de 4 são perdedores para quem joga, se o adversário responder de forma ótima.', application: 'Busca adversarial avalia consequências e respostas possíveis.', limit: 'São algoritmos programados, não modelos de IA competindo. A conclusão vale para as regras deste jogo.', conclusion: 'O resto de uma divisão pode esconder a estratégia.', color: '#bda9ef', minutes: 8 },
  { id: 6, title: 'O relógio das posições', short: 'Módulo & RoPE', math: 'Aritmética modular e rotações', question: 'Um relógio marca 2. Que posição terá após 14 horas?', example: 'Cada volta completa retorna à mesma classe de restos.', prediction: 'O resultado é 2, 4 ou 14?', variant: 'Mude o tamanho do relógio e observe a mesma soma.', reveal: '(2 + 14) mod 12 = 4. Posições equivalentes têm o mesmo resto.', application: 'RoPE usa rotações para incorporar posições em pares de componentes de queries e keys.', limit: 'RoPE usa múltiplas frequências e vetores; não é apenas posição módulo n. O relógio é uma ponte didática.', conclusion: 'Posições organizam sequências; dependências organizam trabalho.', color: '#c1a8f4', minutes: 8 },
  { id: 7, title: 'A cidade das tarefas', short: 'DAGs & agentes', math: 'Dependências e ordens parciais', question: 'Quais tarefas podem acontecer juntas sem atropelar uma dependência?', example: 'Pesquisar → verificar e redigir → revisar.', prediction: 'O que acontece se pesquisar também depender de revisar?', variant: 'Insira o ciclo e depois remova a dependência problemática.', reveal: 'Uma ordenação topológica existe em DAGs. A alcançabilidade define uma ordem estrita, e sua versão reflexiva é uma ordem parcial.', application: 'Fluxos de agentes e pipelines organizam tarefas por dependências.', limit: 'As arestas são dependências diretas; a relação de ordem inclui caminhos transitivos. Agentes aqui são simulados.', conclusion: 'Mesmo um fluxo bem ordenado encontra limites de recursos.', color: '#68d8c4', minutes: 8 },
  { id: 8, title: 'As gavetas impossíveis', short: 'Gavetas & hash', math: 'Princípio das Casas dos Pombos', question: 'É possível distribuir 5 objetos em 4 gavetas sem repetir uma gaveta?', example: 'Cada objeto é colocado em exatamente uma gaveta.', prediction: 'Qual é o primeiro número de objetos que garante alguma colisão?', variant: 'Compare uma distribuição manual com h(x) = x mod g.', reveal: 'Se n > g, pelo menos uma gaveta recebe dois objetos. Em geral, alguma recebe ao menos ⌈n/g⌉.', application: 'Mais entradas possíveis do que hashes disponíveis tornam colisões inevitáveis.', limit: 'n ≤ g não impede colisões; apenas deixa de garanti-las. Colisão de hash não significa igualdade das entradas.', conclusion: 'Limites determinísticos são diferentes de incerteza probabilística.', color: '#edb877', minutes: 8 },
  { id: 9, title: 'O painel das probabilidades', short: 'Probabilidade', math: 'Distribuição e amostragem', question: 'O resultado mais provável precisa aparecer em toda tentativa?', example: 'Quatro tokens possuem pesos que somam 100% após normalização.', prediction: 'Em 100 amostras, as frequências serão exatamente iguais às probabilidades?', variant: 'Aumente a temperatura e repita a amostragem com a mesma semente.', reveal: 'Softmax com temperatura redistribui o peso. Frequências observadas variam por amostragem.', application: 'A geração pode amostrar o próximo token de uma distribuição discreta.', limit: 'Probabilidade de um token não é probabilidade de uma afirmação ser verdadeira. Os logits são ilustrativos.', conclusion: 'Uma escolha também pode ser um evento que muda um estado.', color: '#ef92ac', minutes: 8 },
  { id: 10, title: 'A máquina de estados', short: 'Autômatos', math: 'Estados e transições', question: 'Um assistente pode entregar uma resposta antes de validar a solicitação?', example: 'Receber → validar → responder → concluir; erros podem exigir revisão.', prediction: 'O que deve acontecer se “enviar” chegar no estado inicial?', variant: 'Provoque uma transição inválida e compare com o fluxo correto.', reveal: 'Uma função de transição associa estado e evento a um próximo estado permitido.', application: 'Máquinas de estados controlam fluxos de atendimento e ferramentas.', limit: 'Isso descreve o controle do software, não toda a computação de um modelo de linguagem.', conclusion: 'Mais estados possíveis podem tornar a exploração cara.', color: '#7bcde1', minutes: 8 },
  { id: 11, title: 'A explosão combinatória', short: 'Complexidade', math: 'Crescimento e custo de busca', question: 'Se funciona com 8 elementos, também funciona com 40?', example: 'Compare n, n², 2ⁿ e n! para o mesmo tamanho de entrada.', prediction: 'Qual família ultrapassa primeiro um milhão de possibilidades?', variant: 'Dobre n e compare a mudança em cada família.', reveal: 'As curvas têm taxas de crescimento diferentes. Contar estados não é medir tempo de execução.', application: 'Busca, planejamento e otimização precisam limitar ou explorar melhor seus espaços.', limit: 'Medições são locais e pequenas. Tempos maiores usam uma taxa hipotética, não um benchmark de IA.', conclusion: 'Agora combinamos busca, regras e recursos em uma missão.', color: '#f2c675', minutes: 8 },
  { id: 12, title: 'A missão SYNAPSE', short: 'Missão integrada', math: 'Decidir, buscar, ordenar e limitar', question: 'Sua equipe consegue entregar uma resposta verificada com recursos limitados?', example: 'Um pedido precisa de autorização, fonte alcançável, tarefas sem ciclo e espaço para evidências.', prediction: 'Qual condição vai bloquear a primeira tentativa?', variant: 'Corrija um bloqueio por vez e execute novamente.', reveal: 'A missão só conclui quando lógica, caminho, dependências e capacidade são satisfeitos.', application: 'Sistemas de IA confiáveis combinam vários mecanismos verificáveis ao redor do modelo.', limit: 'A missão é um sistema didático determinístico; não garante qualidade semântica de respostas reais.', conclusion: 'A inteligência do sistema também está na organização ao redor dele.', color: '#67dbb7', minutes: 8 },
  { id: 13, title: 'O desafio da turma', short: 'Desafio final', math: 'Prever antes de revelar', question: 'Qual decisão você defenderia agora?', example: 'Seis situações curtas. A turma vota levantando a mão.', prediction: 'Escolha A, B ou C antes de revelar cada explicação.', variant: 'Peça a alguém que votou diferente para defender a alternativa.', reveal: 'A resposta importa; o motivo que a sustenta importa mais.', application: 'Reconhecer limites e contraexemplos ajuda a avaliar sistemas de IA.', limit: 'Não usamos aparência de texto para alegar autoria humana ou artificial.', conclusion: 'A matemática torna decisões discutíveis, testáveis e corrigíveis.', color: '#c4b0ef', minutes: 10 },
  { id: 14, title: 'As peças agora se conectam', short: 'Síntese & perguntas', math: 'Da abstração ao sistema', question: 'Qual conceito mudou sua forma de olhar para a IA?', example: 'Escolhas → busca → regras → relações → estratégias → posições → dependências → limites → amostragem → estados.', prediction: 'Qual desses conceitos você usaria primeiro em seu próximo projeto?', variant: 'Escolha um problema da turma e identifique duas conexões matemáticas.', reveal: 'Não há uma única matemática da IA. Há mecanismos distintos com hipóteses e limites.', application: 'Engenharia de software combina modelos, algoritmos, dados e verificação.', limit: 'O mapeamento com a ementa do professor ainda precisa ser validado.', conclusion: 'Pergunte. Modele. Preveja. Teste. Explique.', color: '#7fdbc9', minutes: 6 },
];
export const LESSONS: Lesson[] = FORMAL_LESSONS.map(lesson => ({ ...lesson, ...AUDIENCE_COPY[lesson.id] }));
export const QUIZ = [
  { question: '3 símbolos em 4 posições, com repetição: quantas sequências?', options: ['12', '64', '81'], answer: 2, why: 'São quatro escolhas independentes com três opções: 3⁴ = 81.' },
  { question: 'Num labirinto em que cada passo custa o mesmo, como encontrar a rota mais curta?', options: ['Explorar primeiro os lugares próximos', 'Seguir um corredor até o fim', 'Escolher qualquer caminho'], answer: 0, why: 'A busca em largura explora por distância. Aqui, cada passo tem o mesmo custo.' },
  { question: 'Ana espera Bruno, Bruno espera Carla e Carla espera Ana. Alguém consegue começar?', options: ['Sim, Ana', 'Não, todos estão esperando', 'Sim, Carla'], answer: 1, why: 'A espera forma um círculo. Precisamos mudar pelo menos uma dependência para começar.' },
  { question: 'Cinco celulares em quatro gavetas. O que vai acontecer?', options: ['Todos ficam juntos', 'Cada um fica sozinho', 'Alguma gaveta terá pelo menos dois'], answer: 2, why: 'Há mais celulares do que gavetas. Pelo menos uma precisa ser compartilhada.' },
  { question: 'Todo gato é um animal. Então todo animal é um gato?', options: ['Sim', 'Não, a relação não vale ao contrário', 'Só se for pequeno'], answer: 1, why: 'Uma regra em um sentido não garante a regra inversa. Um cachorro é um animal e não é um gato.' },
  { question: 'A IA escolhe uma continuação muito provável. Isso garante uma resposta verdadeira?', options: ['Não, ainda precisamos conferir', 'Sim', 'Sim, se repetir a resposta'], answer: 0, why: 'Uma frase pode soar natural e estar errada. A chance de escolher palavras não mede a verdade de uma afirmação.' },
];
